language: python
python:
  - "2.7"
install:
  - pip install coveralls
script:
  - coverage run test.py
  - coverage run -a load.py -l stdlib.lisp bq.lisp -t test-composition.lisp
  - coverage report -m
  - python load.py -l stdlib.lisp bq.lisp -t test-stdlib.lisp test-bq.lisp
after_success:
  coveralls
